title: "Чат FURRY / ФУРРИ"
description: "Самый современный чат для FURRY / ФУРРИ. Интересные обсуждения, ролевые игры, ивенты, стримы, библиотека, архив изображений, добрая администрация!"
lang: "ru_RU"
logo: "https://cdn-storage.github.io/images/logos/furry.01.001.512.svg.bg.png"
image: "https://cdn-storage.github.io/images/logos/furry.01.001.512.svg.bg.png"

custom:
  keywords: "furry, chat, фурри, чат, фурри чат"
  info:
    url: "https://metainfo.github.io"
  discord:
    url: "https://discord.gg/ShMTyRr"
  stats:
    channels:
      thematic: "10"
      rp: "3"
      voice: "6"
    users: "1300"

twitter:
  username: "furryfdn"
  card: "summary"
social:
  name: "FURRY Foundation"
  links:
    - https://twitter.com/furryfdn
    - https://vk.com/furryfdn

markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed
  sass_dir: assets/css/

author:
  name: "Kitsune Solar"
  email: "kitsune.solar@gmail.com"
  github: "KitsuneSolar"
  twitter: "KitsuneSolar"
